services:
  backend:
    build:
      context: ./
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_USER: admin
      DB_PASSWORD: secret
      DB_NAME: testdb
      DB_HOST: db
      DB_PORT: 5432
    entrypoint: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"